"""adicionar_tabelas_acompanhamento

Revision ID: ff6285b72f48
Revises: 
Create Date: 2026-06-18 15:56:52.845767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ff6285b72f48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('data_publicacao', sa.Date(), nullable=True))
    op.add_column('contratos', sa.Column('prazo_vigencia_dias', sa.Integer(), nullable=True))
    op.add_column('contratos', sa.Column('prazo_execucao_dias', sa.Integer(), nullable=True))
    op.add_column('contratos', sa.Column('gestor_id', sa.UUID(), nullable=True))
    op.add_column('contratos', sa.Column('orgao', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'contratos', 'usuarios', ['gestor_id'], ['id'])
    op.add_column('medicoes', sa.Column('valor_medido', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('medicoes', sa.Column('data_medicao', sa.Date(), nullable=True))
    op.add_column('medicoes', sa.Column('numero_processo_sei', sa.String(length=50), nullable=True))
    op.add_column('obras', sa.Column('data_ordem_servico', sa.Date(), nullable=True))
    op.add_column('obras', sa.Column('gestor_id', sa.UUID(), nullable=True))
    op.add_column('obras', sa.Column('orgao', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'obras', 'usuarios', ['gestor_id'], ['id'])

    # Novas tabelas de acompanhamento
    op.create_table('ordens_servico',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('obra_id', sa.UUID(), nullable=False),
        sa.Column('numero', sa.String(length=50), nullable=False),
        sa.Column('data_emissao', sa.Date(), nullable=False),
        sa.Column('data_inicio', sa.Date(), nullable=True),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('observacao', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('aditivos_prazo',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('obra_id', sa.UUID(), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('dias_adicionados', sa.Integer(), nullable=False),
        sa.Column('nova_data_vigencia', sa.Date(), nullable=False),
        sa.Column('nova_data_execucao', sa.Date(), nullable=False),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('data_assinatura', sa.Date(), nullable=True),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('observacao', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('paralisacoes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('obra_id', sa.UUID(), nullable=False),
        sa.Column('tipo', sa.Enum('PARALISACAO', 'REINICIO', name='tipo_paralisacao_enum'), nullable=False),
        sa.Column('data_evento', sa.Date(), nullable=False),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('saldo_dias_execucao', sa.Integer(), nullable=True),
        sa.Column('saldo_dias_vigencia', sa.Integer(), nullable=True),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('motivo', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('readequacoes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('obra_id', sa.UUID(), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('tipo', sa.Enum('COM_REFLEXO', 'SEM_REFLEXO', name='tipo_readequacao_enum'), nullable=False),
        sa.Column('percentual', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('data_assinatura', sa.Date(), nullable=True),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('observacao', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('apostilamentos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('contrato_id', sa.UUID(), nullable=False),
        sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('data_assinatura', sa.Date(), nullable=True),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('reajustes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('medicao_id', sa.UUID(), nullable=False),
        sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('data_assinatura', sa.Date(), nullable=True),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('observacao', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['medicao_id'], ['medicoes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('termos_recebimento',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('obra_id', sa.UUID(), nullable=False),
        sa.Column('tipo', sa.Enum('PROVISORIO', 'DEFINITIVO', name='tipo_termo_recebimento_enum'), nullable=False),
        sa.Column('numero', sa.String(length=50), nullable=False),
        sa.Column('data_emissao', sa.Date(), nullable=False),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('observacao', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('notificacoes_extrajudiciais',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('obra_id', sa.UUID(), nullable=False),
        sa.Column('empresa_id', sa.UUID(), nullable=False),
        sa.Column('numero', sa.String(length=50), nullable=False),
        sa.Column('data_emissao', sa.Date(), nullable=False),
        sa.Column('data_recebimento', sa.Date(), nullable=True),
        sa.Column('assunto', sa.String(length=300), nullable=False),
        sa.Column('teor', sa.Text(), nullable=True),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['empresa_id'], ['usuarios.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('portarias',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('obra_id', sa.UUID(), nullable=False),
        sa.Column('usuario_id', sa.UUID(), nullable=False),
        sa.Column('tipo', sa.Enum('FISCAL', 'GESTOR', 'OUTROS', name='tipo_portaria_enum'), nullable=False),
        sa.Column('numero', sa.String(length=50), nullable=False),
        sa.Column('data_emissao', sa.Date(), nullable=False),
        sa.Column('data_publicacao', sa.Date(), nullable=True),
        sa.Column('processo_sei', sa.String(length=50), nullable=True),
        sa.Column('observacao', sa.Text(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portarias')
    op.drop_table('notificacoes_extrajudiciais')
    op.drop_table('termos_recebimento')
    op.drop_table('reajustes')
    op.drop_table('apostilamentos')
    op.drop_table('readequacoes')
    op.drop_table('paralisacoes')
    op.drop_table('aditivos_prazo')
    op.drop_table('ordens_servico')

    op.drop_constraint(None, 'obras', type_='foreignkey')
    op.drop_column('obras', 'orgao')
    op.drop_column('obras', 'gestor_id')
    op.drop_column('obras', 'data_ordem_servico')
    op.drop_column('medicoes', 'numero_processo_sei')
    op.drop_column('medicoes', 'data_medicao')
    op.drop_column('medicoes', 'valor_medido')
    op.drop_constraint(None, 'contratos', type_='foreignkey')
    op.drop_column('contratos', 'orgao')
    op.drop_column('contratos', 'gestor_id')
    op.drop_column('contratos', 'prazo_execucao_dias')
    op.drop_column('contratos', 'prazo_vigencia_dias')
    op.drop_column('contratos', 'data_publicacao')
    # ### end Alembic commands ###
